/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grade.horarios;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author helio
 */
public class Principal extends javax.swing.JFrame {

    ArrayList<GradeHorarios> populacao = new ArrayList<>();

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextFieldTamPop = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonRoleta = new javax.swing.JRadioButton();
        jRadioButtonTorneio = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldTamTorneio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextFieldTamPop.setToolTipText("");
        jTextFieldTamPop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTamPopActionPerformed(evt);
            }
        });

        jLabel1.setText("Tamanho População:");

        jLabel2.setText("Método de Seleção:");

        jRadioButtonRoleta.setText("Roleta");
        jRadioButtonRoleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRoletaActionPerformed(evt);
            }
        });

        jRadioButtonTorneio.setText("Torneio");

        jLabel3.setText("Tamanho do Torneio:");

        jTextFieldTamTorneio.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTamPop, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonTorneio)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jRadioButtonRoleta))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldTamTorneio))))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldTamPop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonRoleta)
                    .addComponent(jTextFieldTamTorneio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonTorneio)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        for (int i = 0; i < Integer.parseInt(jTextFieldTamPop.getText()); i++) {
            GradeHorarios novo = new GradeHorarios();
            calculaAptidao(novo);
            novo.atualizaAp();
            novo.mostraAptidao();
            System.out.println("Aptidao: " + novo.getAp());
            populacao.add(novo);

            //System.out.println("Gerou novo individuo!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void calculaAptidao(GradeHorarios grade) {
        int somaHorizontal = 0;
        int somaVertical = 0;
        int aptidaoLinha = 0;
        int aptidaoColuna = 0;
        for (int i = 0; i < 4; i++) {
            for (int j = 0; j < 4; j++) {
                //Turma 1
                if (i == 0 && grade.getGrade()[i][j] == 1 && (j == 0 || j == 1)) {
                    aptidaoLinha++;
                    grade.setAptidao(1, i, j);
                }
                //Turma 2
                if (i == 1 && grade.getGrade()[i][j] == 2 && (j == 3 || j == 1)) {
                    aptidaoLinha = aptidaoLinha + 2;
                    grade.setAptidao(2, i, j);

                }

                //Turma 3
                if (i == 2 && grade.getGrade()[i][j] == 1) {
                    aptidaoLinha++;
                    grade.setAptidao(1, i, j);

                }

                //Turma 4
                if (i == 3 && grade.getGrade()[i][j] == 3 && (j == 0 || j == 2)) {
                    aptidaoLinha = +2;
                    grade.setAptidao(2, i, j);
                }
                somaHorizontal = somaHorizontal + grade.getGrade()[i][j];
                if (somaHorizontal > 3) {
                    aptidaoLinha = 0;
                }

            }
            somaHorizontal = 0;

        }
    }

    public GradeHorarios[] metodo() {
        GradeHorarios[] pais = new GradeHorarios[2];
        if (jRadioButtonRoleta.isSelected()) {
            int num = (int) (Math.random() * (Integer.parseInt(jTextFieldTamPop.getText())));
            int num2 = (int) (Math.random() * (Integer.parseInt(jTextFieldTamPop.getText())));
            
            pais[0]=populacao.get(num);
            pais[1]=populacao.get(num2);
            
        } else if (jRadioButtonTorneio.isSelected()) {
            ArrayList<GradeHorarios> torneio = new ArrayList<>();
            

            Random r = new Random();
            for (int i = 0; i < Integer.parseInt(jTextFieldTamTorneio.getText()); i++) {
                int intermediario = (int) (Math.random() * (Integer.parseInt(jTextFieldTamPop.getText())));
                torneio.add(populacao.get(intermediario));
            }
            Collections.sort(torneio, new Comparator() {
                public int compare(Object o1, Object o2) {
                    GradeHorarios p1 = (GradeHorarios) o1;
                    GradeHorarios p2 = (GradeHorarios) o2;
                    return p1.ap > p2.ap ? -1 : (p1.ap < p2.ap ? +1 : 0);
                }
            });
            pais[0] = torneio.get(0);
            pais[1] = torneio.get(1);
            
            

        } else {
            JOptionPane.showMessageDialog(null, "Informe um metodo");
        }
        return pais;
    }


    private void jTextFieldTamPopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTamPopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTamPopActionPerformed

    private void jRadioButtonRoletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRoletaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonRoletaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButtonRoleta;
    private javax.swing.JRadioButton jRadioButtonTorneio;
    private javax.swing.JTextField jTextFieldTamPop;
    private javax.swing.JTextField jTextFieldTamTorneio;
    // End of variables declaration//GEN-END:variables
}
